tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "osx-cross/avr"
tap "px4/px4"
cask "xquartz"
brew "ansible"
brew "avrdude"
brew "coreutils"
brew "dfu-programmer"
brew "diffutils"
brew "docker-compose"
brew "gawk"
brew "git"
brew "gnu-sed", args: ["with-default-names"]
brew "grep", args: ["with-default-names"]
brew "imagemagick", args: ["with-librsvg"]
brew "mysql"
brew "neovim"
brew "openssh"
brew "postgresql"
brew "pyenv"
brew "python"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "tig"
brew "tmux"
brew "vim", args: ["with-luajit"]
brew "wireshark", link: false
brew "zsh"
brew "heroku/brew/heroku"
brew "osx-cross/avr/avr-gcc"
brew "px4/px4/gcc-arm-none-eabi"
cask "adobe-acrobat-pro"
cask "boostnote"
cask "coteditor"
cask "docker"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-japanese-ime"
cask "microsoft-office"
cask "night-owl"
cask "skype"
cask "slack"
cask "table-tool"
cask "vagrant"
cask "wireshark"
