[[plugins]]
# git の差分表示
repo = 'airblade/vim-gitgutter'
hook_add = '''
set updatetime=100
let g:gitgutter_highlight_lines = 1
'''

[[plugins]]
repo  = 'junegunn/fzf'
build = './install --all'
hook_add = '''
let g:fzf_action = {
            \   'enter': 'tab split',
            \   'ctrl-x': 'split',
            \   'ctrl-v': 'vsplit',
            \ }
'''

[[plugins]]
repo    = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
let g:fzf_buffers_jump = 1

command! -nargs=? -complete=dir Files call FzfFindAll(<f-args>)
nnoremap fa :Files<Space>
nnoremap <silent> ff :GFiles<CR>
nnoremap <silent> f: :History:<CR>
nnoremap <silent> f/ :History/<CR>

" Search normal files and dotfiles with fzf.
function FzfFindAll(...)
    let dir = a:0 ? a:1 : '.'
    call fzf#run(fzf#wrap({ 'source': 'find ' . dir . ' -type f -maxdepth 3' }))
endfunction
'''

# color scheme
[[plugins]]
repo = 'itchyny/landscape.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = 'landscape.vim'
hook_add = '''
set laststatus=2
set showtabline=2

let g:lightline = {}
let g:lightline.colorscheme = 'landscape'
let g:lightline.component_function = {
            \   'cwd': 'LightlineRelativecwd',
            \ }
let g:lightline.tabline = {
            \   'left': [['tabs']],
            \   'right': [['cwd']],
            \ }
let g:lightline.tab_component_function = {
            \   'filename': 'LightlineTabname',
            \ }

function! LightlineRelativecwd()
    return fnamemodify(getcwd(), ':~:.')
endfunction

function! LightlineTabname(n) abort
    let buflist = tabpagebuflist(a:n)
    let winnr = tabpagewinnr(a:n)
    let _ = expand('#'.buflist[winnr - 1])

    if _ ==# ''
        return '[No Name]'
    elseif _ =~# 'bin/fzf'
        return 'fzf'
    else
        return _
    endif
endfunction
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_exclude_filetypes = ['help']
'''

[[plugins]]
# Syntax Highlights
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo  = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'tpope/vim-eunuch'

[[plugins]]
# ANSI color の表示
repo = 'vim-scripts/AnsiEsc.vim'
