[[plugins]]
repo  = 'dense-analysis/ale'
on_ft = [
    'javascript',
    'ruby',
    'rust',
    'scss',
    'slim',
    'terraform',
    'typescript',
    'vue',
]
hook_source = '''
let g:ale_sign_column_always = 1
let g:ale_default_navigation = 'split'
'''

[[plugins]]
repo    = 'kannokanno/previm'
on_ft   = ['markdown']
depends = 'open-browser.vim'

[[plugins]] # dynamic filetype switcher
repo    = 'osyo-manga/vim-precious'
on_ft   = ['eruby', 'help', 'html', 'markdown', 'slim', 'toml']
depends = 'context_filetype.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown']
