#[[plugins]]
#repo     = 'uplus/deoplete-solargraph'
#depends  = 'deoplete.nvim'
#on_event = 'InsertEnter'
#on_ft    = ['ruby']
#hook_post_update = '''
#call system('gem install solargraph')
#call system('pip3 install solargraph-utils.py --user --upgrade')
#call system('yard gems')
#call system('yard config --gem-install-yri')
#'''

[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['pug', 'vue']

[[plugins]]
repo    = 'kannokanno/previm'
on_ft   = ['markdown']
depends = 'open-browser.vim'

[[plugins]]
repo  = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo  = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]] # dynamic filetype switcher
repo    = 'osyo-manga/vim-precious'
on_ft   = ['eruby', 'help', 'html', 'markdown', 'slim', 'toml']
depends = 'context_filetype.vim'

[[plugins]]
repo  = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo  = 'slim-template/vim-slim'
on_ft = ['slim']

[[plugins]]
repo   = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'
on_ft  = ['markdown', 'ruby.rspec', 'sh', 'zsh']
hook_source = '''
let g:quickrun_config = {}
let g:quickrun_config['_'] = {
      \ 'runner': 'vimproc'
      \ }
let g:quickrun_config['markdown'] = {
      \ 'outputter': 'browser'
      \ }
let g:quickrun_config['ruby.rspec'] = {
      \ 'command': 'rspec',
      \ 'exec': 'bundle exec %c %s',
      \ 'cmdopt' : '-c -fd'
      \ }
let g:quickrun_config['sh'] = {
      \ 'command': 'sh',
      \ 'cmdopt' : '-x'
      \ }
let g:quickrun_config['zsh'] = {
      \ 'command': 'source'
      \ }
'''

[[plugins]]
repo = 'tmux-plugins/vim-tmux'
on_ft = ['tmux']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['javascript', 'eruby', 'ruby', 'slim', 'yaml']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['html', 'markdown']

[[plugins]]
repo  = 'w0rp/ale'
on_ft = ['javascript', 'ruby', 'rust', 'slim', 'typescript', 'vue']
hook_source = '''
let g:ale_sign_column_always = 1
let g:ale_completion_enabled = 1
'''
