[[plugins]]
repo   = 'bronson/vim-trailing-whitespace'
on_cmd = 'FixWhitespace'
on_event = 'InsertEnter'

[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = 'lightline.vim'
on_source = 'ale'
hook_source = '''
let g:lightline.component_expand = {
            \   'linter_checking': 'lightline#ale#checking',
            \   'linter_warnings': 'lightline#ale#warnings',
            \   'linter_errors': 'lightline#ale#errors',
            \   'linter_ok': 'lightline#ale#ok',
            \ }
let g:lightline.component_type = {
            \   'linter_checking': 'left',
            \   'linter_warnings': 'warning',
            \   'linter_errors': 'error',
            \   'linter_ok': 'left',
            \ }
let g:lightline.active = {
            \ 'left': [
            \     [ 'mode', 'paste' ],
            \     [ 'readonly', 'filename', 'modified' ],
            \     [ 'linter_checking', 'linter_errors', 'linter_warnings', 'linter_ok' ]
            \   ]
            \ }
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
depends = 'context_filetype.vim'
hook_source = '''
set completeopt+=noinsert
call deoplete#enable()
'''

[[plugins]]
repo = 'tpope/vim-endwise'
on_event = 'InsertEnter'
