#!/usr/bin/env bash

EXPECTED_NAME='epaew'
EXPECTED_EMAIL='epaew.333@gmail.com'

check_git_config () {
  key=$1
  expected=$2
  current=$(git config $key)

  [[ $current == $expected ]]
  return $?
}

check_git_user () {
  check_git_config 'user.name' $EXPECTED_NAME
  is_name_expected=$?
  check_git_config 'user.email' $EXPECTED_EMAIL
  is_email_expected=$?

  return $is_name_expected && $is_email_expected
}

set_git_config () {
  key=$1
  expected=$2

  git config $key $expected >/dev/null
}

set_git_user () {
  set_git_config 'user.name' $EXPECTED_NAME
  set_git_config 'user.email' $EXPECTED_EMAIL
  echo 'User updated. Please try again.' >&2
  exit 1
}

check_and_set_git_user () {
  origin=$(git config remote.origin.url)
  case $origin in
    *github.com* ) check_git_user || set_git_user ;;
  esac
}

main () {
  check_and_set_git_user
}

main
