#!/usr/bin/env bash

# 使い方
# 1. `.git/hooks/prepare-commit-msg` にこのスクリプトを置く
# 2. ↓の `PREFIX` をセットする

PREFIX='' # Set the issue prefix
FILE_NAME=$1

branch_name=$(git rev-parse --abbrev-ref HEAD)
if [[ $PREFIX == '' ]]; then
  echo '$PREFIX is empty' >&2
  exit 1
elif [[ $branch_name =~ $PREFIX ]]; then
  original_message=$(cat $FILE_NAME)
  prefix_with_number=$(echo $branch_name | grep -o -E "${PREFIX}-[[:digit:]]+")
  if [[ $original_message =~ ^${prefix_with_number} ]]; then exit 0; fi

  echo "${prefix_with_number}: ${original_message}" > $FILE_NAME
fi
